FPS = 1 / 30

GRID_WIDTH = 40
GRID_HEIGHT = 40

MIN_ROOM_WIDTH = 4
# MAX_ROOM_WIDTH = 5
MAX_ROOM_WIDTH = 10
MIN_ROOM_HEIGHT = 4
# MAX_ROOM_HEIGHT = 5
MAX_ROOM_HEIGHT = 10
MIN_ROOM_SIZE = MIN_ROOM_WIDTH * MIN_ROOM_HEIGHT
MAX_ROOM_SIZE = MAX_ROOM_WIDTH * MAX_ROOM_HEIGHT

ROOM_CREATION_MAX_ATTEMPTS = 500
ROOM_OPTIMIZATION_MAX_ATTEMPTS = 10

NORTH_RATIO = (0, -1)
SOUTH_RATIO = (0, 1)
EAST_RATIO = (1, 0)
WEST_RATIO = (-1, 0)

INK_PROBALITIES = [0, 1, 1, 1, 2]
